#!/bin/bash
# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

# spawns a template

# Checks in a specified template folder for a given template name and copies it
# to the current directory. If a filename is given as a second argument, it is
# copied there instead. If no template could be found, `find` is used to find a
# template starting with that name. The user is then asked whether he wanted
# that file.

if [[ -z "$1" ]]
then
	echo "usage: spawn <templatename>"
	exit 1
fi

templatepath=~/Vorlagen
if [[ ! -d "$templatepath" ]]
then
	echo "$templatepath does not exist."
	exit 2
fi

selected="$templatepath/${1}"

spawn-it() {
	if [[ -z "$2" ]]
	then
		target=$(basename "$1")
	else
		target="$2"
	fi

	cat "$1" | sed "s/YEAR/$(date +%Y)/" > "$target"
}

if [[ ! -f "$selected" ]]
then
	candidates=$(find "$templatepath" -type f -name "$1*" | wc -l)
	likely=$(find "$templatepath" -type f -name "$1*")
	if ((candiates == 1))
	then
		spawn-it "$likely" "$2"
	elif ((candidates == 0))
	then
		echo "No template like that."
		exit 3
	else
		echo "Ambigious template. Could be $(echo "$likely" | tr '\n' ' ')."
		exit 4
	fi
else
	spawn-it "$selected" "$2"
fi
