#!/bin/bash
# Copyright (c) 2011-2012 Martin Ueding <dev@martin-ueding.de>

# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.

# Spawns a template.

# Checks in a specified template folder for a given template name and copies it
# to the current directory. If a filename is given as a second argument, it is
# copied there instead. If no template could be found, `find` is used to find a
# template starting with that name. The user is then asked whether he wanted
# that file.

if [[ -z "$1" ]]
then
	echo "usage: spawn <templatename>"
	exit 1
fi

templatepath=~/Vorlagen
if [[ ! -d "$templatepath" ]]
then
	echo "$templatepath does not exist."
	exit 2
fi

selected="$templatepath/${1}"

spawn-it() {
	if [[ ! -f "$1" ]]
	then
		exit 1
	fi

	source="$1"

	if [[ -z "$2" ]]
	then
		target=$(basename "$source")
	else
		target="$2"
	fi

	if [[ -f "$target" ]]
	then
		if diff "$source" "$target" > /dev/null
		then
			echo "The file already exists but is the same."
		else
			echo "The file already exists and differs."
			select selection in "exit" "replace" "diff"
			do
				echo "$selection -- $REPLY"
				case "$selection" in
					exit)
						exit 0
						;;
					replace)
						break
						;;
					diff)
						diff -u "$source" "$target"
						;;
				esac
			done
		fi
	fi

	cat "$source" | sed "s/YEAR/$(date +%Y)/" > "$target"
}

if [[ ! -f "$selected" ]]
then
	candidates=$(find "$templatepath" -type f -name "$1*" | wc -l)
	likely=$(find "$templatepath" -type f -name "$1*")
	if ((candiates = 1))
	then
		spawn-it "$likely" "$2"
	elif ((candidates = 0))
	then
		echo "No template like that."
		exit 3
	else
		echo "Ambigious template. Could be $(echo "$likely" | tr '\n' ' ')."
		exit 4
	fi
else
	spawn-it "$selected" "$2"
fi
